<!-- 
    - 자바 프로그램 작성시 자바 문법에 맞지 않게 코드를 작성하고 컴파일하려고 하면, 자바 컴파일러는 문법 오류(syntax eroor) 발생 시킴
    - 자바 문법에 맞게 작성되었더라도 프로그램 실행되면서 예상 못한 오류 발생 가능
    - 컴퓨터 시스템이 동작하는 중 예상치 못한 사태가 발생해 실행 중인 프로그램이 영향을 받는 것을 2가지로 분류

    - 오류(error)
        - 시스템 레벨에서 프로그램에 심각한 문제를 야기하여 실행 중인 프로그램 종료 시킴
        - 개발자가 미리 예측하여 처리할 수 없는 것이 대부분이므로 오류에 대한 처리는 할 수 없음

    - 예외(exception)
        - 오류와 마찬가지로 실행 중인 프로그램을 비정상적으로 종료시킴
        - 발생할 수 있는 상황을 미리 예측하여 처리 가능

예외 처리(exception handling)
    - 프로그램이 실행되는 도중 발생하는 예외를 처리하기 위해 사용

    try {
        // 맨 먼저 실행되는 코드 (여기서 발생한 예외는 catch 블록에서 처리됨)
    } catch (e1) {
        // e1 예외가 발생할 경우 실행될 코드; (예외 코드나 예외 객체를 인수로 전달받아 그 처리를 담당)
    } catch (e2) {
        // e2 예외가 발생할 경우 실행될 코드;   
    }
    ...
    finally {
        // try 블록에서 예외가 발생하든 안하든 맨 마지막에 무조건 실행
    }

try 구문
    - catch 블록과 finally 블록은 선택적인 옵션
    - try / catch
    - try / finally
    - try / catch / finally

예외처리 메커니즘
    1. try 블록에 도달한 프로그램의 제어는 try 블록 내의 코드를 실행함
        이때 만약 예외가 발생(throw)하지 않고, finally 블록이 존재하면 프로그램의 제어는 finally 블록으로 이동함

    2. try 블록에서 예외가 발생하면, catch 핸들러는 다음과 같은 순서로 적절한 catch 블록을 찾게 됨
        2-1. 스택에서 try 블록과 가장 가까운 catch 블록부터 차례대로 검사
        2-2. 적절한 catch 블록을 찾지 못하면, 바로 다음 try 블록 다음에 위치한 catch 블록을 차례대로 검사
        2-3. 이러한 과정을 가장 바깥쪽 try 블록까지 계속 검사
        2-4. 그래도 적절한 catch 블록을 찾지 못하면, 예외는 처리되지 못함

    3. 만약 적절한 catch 블록을 찾게 되면, throw 문의 피연산자는 예외 객체의 형식 매개변수로 전달됨

    4. 모든 예외 처리가 끝나면 프로그램의 제어는 finally 블록으로 이동

    5. fianlly 블록이 모두 처리되면, 프로그램의 제어는 예외 처리문 바로 다음으로 이동

    - 모든 catch 블록이 해당 예외를 처리할 수 없으면, 예외는 처리되지 못한 채 해당 프로그램은 강제 종료됨



예외 클래스

    Exception 클래스
        - 자바의 모든 예외의 조상 클래스

        RuntimeException 클래스
            - RuntimeException 클래스를 상속받는 자식 클래스들은 주로 치명적인 예외 사항을 발생시키지 않는 예외들로 구성
            - try / catch 문 사용보다 프로그램 작성하면서 예외가 발생하지 않도록 주의

        그 외 Exception 클래스의 자식 클래스
            - 치명적인 예외 사항 발생시키므로 try / catch 문으로 처리해야 함
            - 자바 컴파일러는 RuntimeException 클래스 이외의 Exception 클래스의 자식 클래스에 속하는 예외가 발생할 가능성이 있는 구문에는 반드시 예외 처리하도록 강제하고 있음

            public class Exception01 {
                public static void main(String[] args) {
                    byte[] list = {'a', 'b', 'c'};

                    try {
                        System.out.write(list);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }

예외 처리 계층 관계
    - 자바에서 예외가 발생하면 try 블록과 가장 가까운 catch 블록부터 순서대로 검사함

    try {
        System.out.write(list);
    } catch (Exception e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }

    try {
        this.db.commit();
    } catch (IOException | SQLException e) {            // 둘 이상의 예외 타입을 동시에 처리하는 매개변수로 전달받은 예외 객체는 묵시적으로 final 제어자를 가지게 됨 (어떤 값도 대입 불가)
        e.printStackTrace();
    }

Throwable 클래스
    - 모든 예외의 조상이 되는 Exception 클래스와 모든 오류의 조상이 되는 Error 클래스의 부모 클래스
    - Throwable 타입과 이 클래스를 상속받은 서브 타입만이 자바 가상 머신(JVM)이나 throw 키워드에 의해 던져질 수 있음

    - String getMessage() : 해당 throwable 객체에 대한 자세한 내용을 문자열로 반환

    - void printStackTrace() : 해당 throwable 객체와 표준 오류 스트림(standard error stream)에서 해당 객체의 스택 트레이스(stack trace)를 출력

    - String toString() : 해당 throwable 객체에 대한 간략한 내용을 문자열로 반환

    try {
        sout(5 / 0);
    } catch (ArithmeticException e) {
        sout("예외: " + e.getMessage());
    }

    => 예외: by zero

자주 사용되는 예외 클래스
    - ClassCastException : 수행할 수 없는 타입 변환이 진행될 경우

    - ArrayIndexOutOfBoundsException : 배열에 잘못된 인덱스를 사용하여 접근할 경우

    - NullPointerException : null 객체의 인스턴스 메소드를 호출하는 경우

    - ArithmeticException : 산술 연산에서 정수를 0으로 나누는 등 연산을 수행할 수 없는 경우

예외 발생시키기
    - throw 키워드로 강제로 예외 발생 시킬 수 있음
    - Exception e = new Exception("오류메시지");
    - throw e;

예외 회피하기
    - 메소드 선언부에 throws 키워드를 사용하여 해당 메소드를 사용할 때 발생할 수 있는 예외를 미리 명시할 수 있음
    - 해당 메소드를 사용할 때 발생할 수 있는 예외를 사용자가 충분히 인지할 수 있고 그에 대한 처리까지도 강제할 수 있음

    public class Exception {
        static void handlingException() {
            try {
                throw new Exception();
            } catch (Exception e) {
                sout("호출된 메소드에서 예외 처리됨")
            }
        }

        public static void main(String[] args) {
            try {
                handlingException();
            } catch (Exception e) {
                sout("main 메소드에서 예외 처리됨")
            }
        }
    }


    public class Exception {
        static void handlingException() throws Exception { throw new Exception(); }

        public static void main(String[] args) {
            try {
                handlingException();
            } catch (Exception e) {
                sout("main 메소드에서 예외 처리됨")
            }
        }
    }

사용자 정의 예외 클래스
    - Exception 클래스를 상속받아 자신만의 새로운 예외 클래스를 정의해 사용할 수 있음
    - 생성자 뿐만 아니라 필드 및 메소드도 원하는 만큼 추가할 수 있음

    class MyException extends RuntimeException {
        MyException(String errMsg) {
            super(errMsg);
        }
    }

try-with-resources 문
    - 사용한 자원을 자동으로 해제
    - try 블록에 괄호를 추가하여 파일을 열거나 자원을 할당하는 명령문을 명시하면, 해당 try 블록이 끝나자마자 자동으로 파일을 닫거나 할당된 자원을 해제해 줌
    - try (파일을열거나자원을할당하는명령문) { ... }

    static String readFile(String filePath) throws IOException {
        BufferedReader br = new BufferedReader(new FileReader(filePath));

        try {
            return br.readLine();
        } finally {
            if (br != null) br.close();
        }
    }

    ↑ JAVA SE 7 이전, finally 블록을 사용하여 사용한 파일을 닫아줘야 했으나

    static String readFile(String filePath) throws IOException {
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            return br.readLine();
        }
    }

    ↑ JAVA SE 7 이후, () 자동 파일 닫기 수행됨

-->